name: fatiando-data-caribbean-bathymetry
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - numpy
  - jupyterlab
  - ipykernel
  - matplotlib
  - pyproj
  # PyGMT for plotting
  - pygmt==0.11.0
  - gmt==6.5.0
  # Fatiando
  - pooch>=1.0
  - verde==1.8.0
